<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>@yield('title') - {{ config('app.name') }}</title>

        <link rel="stylesheet" type="text/css" href="{{ url('assets/css/app.css') }}">
    </head>
    <body>
        <div class="top">
            <div class="logo"></div>

            <div class="tagline">
                {{ config('app.name') }}
            </div>
        </div>

        <div class="content">
            @yield('content')
        </div>

        <div class="footer">
            Generated by {{ config('app.codename') }}. Good bot.
        </div>
    </body>
</html>
