<!DOCTYPE html>
<html lang="{{ config('app.locale') }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <meta name="csrf-param" content="_token">

        <script>
            window.Laravel = {!! json_encode([
                'csrfToken' => csrf_token(),
            ]) !!};
        </script>

        <title>@yield('title') - {{ config('app.name') }}</title>

        <link rel="stylesheet" type="text/css" href="{{ url('css/foundation.min.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url('css/foundation-icons.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ url('css/app.css') }}">
    </head>
    <body>
        <div id="app"></div>
        <header class="header">
            <a href="{{ route('forum.index') }}"><div class="logo"></div></a>
            <a href="{{ route('forum.index') }}"><h1 class="headline">{{ config('app.name') }} <small class="show-for-medium">{{ config('app.tagline') }}</small></h1></a>

            @include('layouts.navigation')
        </header>

        <div class="main">
            @yield('main')

            <footer class="footer show-for-medium">
                Generated by {{ config('app.codename') }}. Good boy.
            </footer>
        </div>
    </body>
</html>
